version: "3"
services:
  app:
    build: .
    image: zaseki-img
    container_name: zaseki-app
    ports:
      - 8000:8000
    volumes:
      - ./zaseki:/zaseki
    working_dir: /zaseki
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres
    container_name: zaseki-db
    ports:
      - 5432:5432
    volumes:
      - db-vol:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: vagrant
      POSTGRES_PASSWORD: vagrant
      POSTGRES_DB: zaseki_db
volumes:
  db-vol: