# Generated by Django 3.2 on 2022-07-13 17:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_name', models.CharField(max_length=100, verbose_name='レイアウト名')),
                ('layout_width', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='レイアウト横幅(px)')),
                ('layout_height', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='レイアウト縦幅(px)')),
                ('seat_width', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='座席横幅(px)')),
                ('seat_height', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='座席縦幅(px)')),
                ('font_size', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='フォントサイズ(px)')),
                ('opacity', models.DecimalField(decimal_places=2, default=0.8, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='不透明度')),
                ('non_sitting_seat_color', models.CharField(default='#25C964', max_length=7, validators=[django.core.validators.RegexValidator(regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='空席(色)')),
                ('sitting_seat_color', models.CharField(default='#FF6699', max_length=7, validators=[django.core.validators.RegexValidator(regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='満席(色)')),
                ('notice', models.TextField(blank=True, max_length=1000, verbose_name='注意事項')),
                ('image', models.ImageField(upload_to='', verbose_name='レイアウト画像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layout_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layout_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name_plural': 'レイアウト',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coordinate', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='X座標(px)')),
                ('y_coordinate', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Y座標(px)')),
                ('is_used', models.BooleanField(default=False, verbose_name='使用中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat_created_by', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('layout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seats.layout', verbose_name='レイアウト')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name_plural': '座席',
            },
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sit_datetime', models.DateTimeField(auto_now_add=True, verbose_name='着席日時')),
                ('seat', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seats.seat')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '利用状況',
            },
        ),
        migrations.AddField(
            model_name='seat',
            name='user',
            field=models.ManyToManyField(through='seats.Usage', to=settings.AUTH_USER_MODEL, verbose_name='使用者'),
        ),
    ]
