# Generated by Django 3.2 on 2022-07-30 08:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import seats.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='image',
            field=models.ImageField(upload_to=seats.models.Layout.get_image_path, verbose_name='レイアウト画像'),
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coordinate', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('y_coordinate', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('sit_datetime', models.DateTimeField(blank=True, null=True, verbose_name='着席日時')),
                ('leave_datetime', models.DateTimeField(blank=True, null=True, verbose_name='離席日時')),
                ('layout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seats.layout')),
                ('seat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seats.seat')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '利用履歴',
            },
        ),
    ]
